### ISSUE TITLE
[Bug]:  Phonon calculation failure

### ISSUE THREAD

**Issue by Frank-LIU-520** [microsoft/mattersim#49]
### Bug Description

When I try to calculate the phonon dispersion according to the tutorial, there is no where to find the output and the /tmp/phonon_si_example folder. Below is the output of my screen.

'''
/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
2024-12-04 12:25:59,092 - INFO - Loading the pre-trained mattersim-v1.0.0-1M.pth model
Supercell matrix for 2nd force constants :
[[4 0 0]
 [0 4 0]
 [0 0 4]]
/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['transformation_matrix']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['international']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['rotations']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['translations']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['number']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['wyckoffs']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['equivalent_atoms']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(

Inferring forces for displaced atoms and computing fcs ...
100%|██████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.08s/it]
Max drift of force constants: -0.000006 (xx) -0.000006 (xx)
Max drift after symmetrization by translation: -0.000000 (xx) -0.000000 (xx)
Qpoints mesh for Brillouin Zone integration : [24 24 24]
Dispersion relations using phonopy for Si2 ...

/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['std_lattice']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['std_positions']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['std_types']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['std_rotation_matrix']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['international']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['number']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['hall']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
Has imaginary phonon: False
Phonon frequencies: <phonopy.api_phonopy.Phonopy object at 0x7f5efdd81640>
'''

### MatterSim Version

default

### Python Version

3.9

### Reproduction Steps

1. install 
2. run code according to 'https://microsoft.github.io/mattersim/examples/phonon_example.html'
3. no output generated

### Expected Behavior

generate the output in the folder

### Actual Behavior

nothing in the folder

### Error Logs

```python
'''
/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
2024-12-04 12:25:59,092 - INFO - Loading the pre-trained mattersim-v1.0.0-1M.pth model
Supercell matrix for 2nd force constants :
[[4 0 0]
 [0 4 0]
 [0 0 4]]
/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['transformation_matrix']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['international']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['rotations']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['translations']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['number']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['wyckoffs']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['equivalent_atoms']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(


Inferring forces for displaced atoms and computing fcs ...
100%|██████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.08s/it]
Max drift of force constants: -0.000006 (xx) -0.000006 (xx)
Max drift after symmetrization by translation: -0.000000 (xx) -0.000000 (xx)
Qpoints mesh for Brillouin Zone integration : [24 24 24]
Dispersion relations using phonopy for Si2 ...

/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['std_lattice']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['std_positions']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['std_types']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['std_rotation_matrix']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['international']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['number']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/ztliu/anaconda3/envs/mattersim/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['hall']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
Has imaginary phonon: False
Phonon frequencies: <phonopy.api_phonopy.Phonopy object at 0x7f5efdd81640>
'''
```

### Code of Conduct

- [x] I agree to follow the project's Code of Conduct

**Comment by yanghan234** [comment]
Hi @Frank-LIU-520, 

In the phonon example, the phonon plots are saved in the `/tmp/phonon_si_example` folder. Would you please check if you have this folder on your machine? 

If you cannot find this folder, please try to set the `work_dir` parameter to `'./'`, which will save the phonon plots in your current directory. 

https://github.com/microsoft/mattersim/blob/b693716b766c282370a849dc7922da38c2f89b4d/src/mattersim/applications/phonon.py#L19-L34

Please let us know if this solves your issue. Thanks

**Comment by Frank-LIU-520** [comment]
Worked for me. Thank you, Han.

**Comment by yanghan234** [comment]
Thank you @Frank-LIU-520, I'll close this.
