### ISSUE TITLE
[Feat]: models trained with graphormer architecture

### ISSUE THREAD

**Issue by zdcao121** [microsoft/mattersim#51]
### Feature Description

It appears that only the models trained with the M3GNet architecture have been released. In the paper, the model based on the `Graphormer` architecture seems more promising. I’m curious when they will be made open-source for the community.

### Motivation

The model based on `Graphormer` architecture is more promising and is expected to have broader applications.

### Contribution Interest

- [ ] I'm interested in potentially implementing this feature
- [ ] I can provide guidance, but cannot implement
- [x] I'm just suggesting the feature for the community

### Code of Conduct

- [x] I agree to follow the project's Code of Conduct

**Comment by luzihen** [comment]
Currently, MatterSimV1-1M and MatterSimV1-5M are released to be used/built on. We are continuing to refine and enhance other versions of MatterSim that we are looking to make available in the future. We are looking forward to learning from the materials community and how we can improve our work together. For now, more advanced and fully-supported versions of MatterSim, and additional materials capabilities are available in Azure Quantum Elements. If you have further questions, please email us at ai4s-materials@microsoft.com.
