### ISSUE TITLE
[Bug]: Cell Vectors are too small ignores cases where cell vectors can be negative

### ISSUE THREAD

**Issue by dundarphys** [microsoft/mattersim#52]
### Contact Details

dundarwork@gmail.com

### Bug Description

At /datasets/utils/convertor.py line 210:
there is an if statement 
if np.all(atoms.cell < 1 e-5):
raise value error ...

In this statement expected to be lattice vectors are positive. however any crystal can be defined using negative lattice vectors. 
this statement should be 
np.all(abs(atoms.cell) < 1 e-5) 
to reflect this fact.

### MatterSim Version

1

### Python Version

3.9

### Reproduction Steps

It appears when all lattice vectors are negative

### Expected Behavior

it should be able to calculate

### Actual Behavior

it raises value error

### Error Logs

```python
Raise value error
```

### Code of Conduct

- [x] I agree to follow the project's Code of Conduct

**Comment by yanghan234** [comment]
Thank you @dundarphys, we have fixed this issue in #53. Please install the latest version from source code, have a try and let us know if this issue is still there.

**Comment by dundarphys** [comment]
Thank you. Bug fixed. It works.
