### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by JaGeo** [microsoft/mattersim#70]
### Bug Description

Thank you for providing the pre-trained models. I am very happy that the community can use them.

It would be great if a new release based on the current git branch could be made. Currently, the emmet requirements of v.1.0.0 block integrating it into other software that I am using. This is fixed on the main branch. Thank you in advance. 

### MatterSim Version

v1.0.0

### Python Version

3.10

### Reproduction Steps

- 

### Expected Behavior

-

### Actual Behavior

-

### Error Logs

```python

```

### Code of Conduct

- [x] I agree to follow the project's Code of Conduct

**Comment by yanghan234** [comment]
Hi @JaGeo, thank you for raising this issue. It seems that you might be experiencing the same problem as mentioned in pull request #61. If that's the case, it has already been resolved.

Please install `mattersim>=1.0.1rc1`, which should address the conflict dependency issues with packages like atomate2.

**Comment by JaGeo** [comment]
Thank you! I will close the issue for now. I did not see the release candidate!
